AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.6.0
  NewCops: enable
  SuggestExtensions: false

Layout/RescueEnsureAlignment:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 25
Metrics/BlockLength:
  Max: 50
Style/MultilineTernaryOperator:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/ParameterAlignment:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 25
Layout/LineLength:
  Max: 120
Style/MultilineBlockChain:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
